### PR TITLE
Update FindGUROBI.cmake (gurobi90 gurobi91)

### PR DESCRIPTION
**Pull request by gasse**
Seems like Gurobi's version number has to be incremented manually after each release... This did the work for me.

### CODE REVIEW

**Comment by matbesancon** [comment]
Thanks! I'll follow-up on the SCIP repo for this one

**Comment by fschloesser** [comment]
Hey @gasse, thank you for the patch!
Since this is a read-only mirror, I'm gonna close this pull request and as @matbesancon said, we will follow-up on this in the development repository.

**Comment by gasse** [comment]
Sure, no problem. Thanks !

**Comment by matbesancon** [comment]
it's merged on the bugfix branch and should be up on this mirror soon-ish

**Pull request closed without merging**
